// Exam-point (考点) seed data. Sourced from Cambridge official format docs:
// - KET A2 Key:   https://www.cambridgeenglish.org/exams-and-tests/qualifications/key/format/
// - PET B1 Prelim: https://www.cambridgeenglish.org/exams-and-tests/qualifications/preliminary/format/
//
// ID scheme: "{examType}.{paperCode}.P{part}"
// paperCode: "RW" (KET combined R&W), "R", "W", "L" (Listening), "S" (Speaking).

export type ExamPointSeed = {
  id: string;
  examType: "KET" | "PET";
  paperCode: string;
  part: number;
  code: string;
  label: string;
  descriptionZh: string;
  skillTags: string[];
};

export const examPoints: ExamPointSeed[] = [
  // ==================== KET Reading & Writing (combined, 7 parts) ====================
  {
    id: "KET.RW.P1",
    examType: "KET",
    paperCode: "RW",
    part: 1,
    code: "RW_P1_matching",
    label: "Matching descriptions to short texts (signs/notices)",
    descriptionZh: "将描述与短文（标识/告示）配对",
    skillTags: ["scanning", "vocabulary", "reading-comprehension"],
  },
  {
    id: "KET.RW.P2",
    examType: "KET",
    paperCode: "RW",
    part: 2,
    code: "RW_P2_open_cloze",
    label: "Open cloze (one word per gap, email/postcard)",
    descriptionZh: "开放式填空（每空一词，邮件/明信片）",
    skillTags: ["grammar", "vocabulary", "function-words", "phrasal-verbs"],
  },
  {
    id: "KET.RW.P3",
    examType: "KET",
    paperCode: "RW",
    part: 3,
    code: "RW_P3_mcq_comprehension",
    label: "Multiple-choice comprehension",
    descriptionZh: "选择题阅读理解",
    skillTags: ["reading-comprehension", "inference", "detail"],
  },
  {
    id: "KET.RW.P4",
    examType: "KET",
    paperCode: "RW",
    part: 4,
    code: "RW_P4_matching_sentences",
    label: "Matching sentences to paragraph descriptions",
    descriptionZh: "将句子与段落描述配对",
    skillTags: ["scanning", "main-ideas"],
  },
  {
    id: "KET.RW.P5",
    examType: "KET",
    paperCode: "RW",
    part: 5,
    code: "RW_P5_mcq_cloze",
    label: "Multiple-choice cloze",
    descriptionZh: "选择填空",
    skillTags: ["grammar", "vocabulary-in-context"],
  },
  {
    id: "KET.RW.P6",
    examType: "KET",
    paperCode: "RW",
    part: 6,
    code: "RW_P6_email",
    label: "Guided email (25+ words, 3 content points)",
    descriptionZh: "指令作文：邮件（不少于 25 词，包含 3 个要点）",
    skillTags: ["writing", "register", "content-points"],
  },
  {
    id: "KET.RW.P7",
    examType: "KET",
    paperCode: "RW",
    part: 7,
    code: "RW_P7_picture_story",
    label: "Picture story (35+ words)",
    descriptionZh: "看图写故事（不少于 35 词）",
    skillTags: ["writing", "narrative", "past-tenses", "sequencing"],
  },

  // ==================== KET Listening (5 parts, Phase 2) ====================
  {
    id: "KET.L.P1",
    examType: "KET",
    paperCode: "L",
    part: 1,
    code: "L_P1_mcq_pictures",
    label: "Multiple-choice with pictures (short dialogues)",
    descriptionZh: "图片选择题（短对话）",
    skillTags: ["listening", "specific-info"],
  },
  {
    id: "KET.L.P2",
    examType: "KET",
    paperCode: "L",
    part: 2,
    code: "L_P2_gap_fill",
    label: "Gap-fill (one word/number/date/time)",
    descriptionZh: "听写填空（单词/数字/日期/时间）",
    skillTags: ["listening", "specific-info", "spelling"],
  },
  {
    id: "KET.L.P3",
    examType: "KET",
    paperCode: "L",
    part: 3,
    code: "L_P3_mcq_longer",
    label: "Multiple-choice (longer interview/narrative)",
    descriptionZh: "选择题（较长访谈/叙述）",
    skillTags: ["listening", "gist", "detail"],
  },
  {
    id: "KET.L.P4",
    examType: "KET",
    paperCode: "L",
    part: 4,
    code: "L_P4_gap_fill_monologue",
    label: "Gap-fill (monologue/interview)",
    descriptionZh: "听写填空（独白/访谈）",
    skillTags: ["listening", "specific-info"],
  },
  {
    id: "KET.L.P5",
    examType: "KET",
    paperCode: "L",
    part: 5,
    code: "L_P5_mcq_monologue",
    label: "Multiple-choice (longer monologue/narrative)",
    descriptionZh: "选择题（较长独白/叙述）",
    skillTags: ["listening", "narrative", "inference"],
  },

  // ==================== KET Speaking (2 parts, Phase 3) ====================
  {
    id: "KET.S.P1",
    examType: "KET",
    paperCode: "S",
    part: 1,
    code: "S_P1_interview",
    label: "Interview with examiner (familiar topics)",
    descriptionZh: "考官面试（熟悉话题）",
    skillTags: ["speaking", "interaction", "pronunciation"],
  },
  {
    id: "KET.S.P2",
    examType: "KET",
    paperCode: "S",
    part: 2,
    code: "S_P2_partner_discussion",
    label: "Discussion with partner (likes/dislikes)",
    descriptionZh: "双人讨论（喜好/观点）",
    skillTags: ["speaking", "interaction", "opinion"],
  },

  // ==================== PET Reading (6 parts) ====================
  {
    id: "PET.R.P1",
    examType: "PET",
    paperCode: "R",
    part: 1,
    code: "R_P1_signs",
    label: "Multiple-choice (signs/notices, 5 options)",
    descriptionZh: "选择题（标识/告示，5 个选项）",
    skillTags: ["reading", "scanning"],
  },
  {
    id: "PET.R.P2",
    examType: "PET",
    paperCode: "R",
    part: 2,
    code: "R_P2_matching",
    label: "Matching people to texts",
    descriptionZh: "将人物与文本配对",
    skillTags: ["reading", "skimming", "main-ideas"],
  },
  {
    id: "PET.R.P3",
    examType: "PET",
    paperCode: "R",
    part: 3,
    code: "R_P3_mcq_comprehension",
    label: "Multiple-choice (longer article/narrative)",
    descriptionZh: "选择题（较长文章/叙述）",
    skillTags: ["reading", "inference", "detail"],
  },
  {
    id: "PET.R.P4",
    examType: "PET",
    paperCode: "R",
    part: 4,
    code: "R_P4_gapped_text",
    label: "Gapped text (sentence insertion)",
    descriptionZh: "段落插句（句子还原）",
    skillTags: ["reading", "discourse", "cohesion"],
  },
  {
    id: "PET.R.P5",
    examType: "PET",
    paperCode: "R",
    part: 5,
    code: "R_P5_mcq_cloze",
    label: "Multiple-choice cloze (collocations, phrasal verbs, discourse)",
    descriptionZh: "选择填空（搭配/短语动词/语篇标记）",
    skillTags: ["vocabulary", "collocations", "phrasal-verbs"],
  },
  {
    id: "PET.R.P6",
    examType: "PET",
    paperCode: "R",
    part: 6,
    code: "R_P6_open_cloze",
    label: "Open cloze (grammar, function words)",
    descriptionZh: "开放式填空（语法/功能词）",
    skillTags: ["grammar", "function-words"],
  },

  // ==================== PET Writing (2 parts) ====================
  {
    id: "PET.W.P1",
    examType: "PET",
    paperCode: "W",
    part: 1,
    code: "W_P1_email",
    label: "Email response (3 content points, ~100 words)",
    descriptionZh: "回信（3 个要点，约 100 词）",
    skillTags: ["writing", "register", "content-points"],
  },
  {
    id: "PET.W.P2",
    examType: "PET",
    paperCode: "W",
    part: 2,
    code: "W_P2_letter_or_story",
    label: "Choice: informal letter OR story (~100 words)",
    descriptionZh: "二选一：非正式信件 或 故事（约 100 词）",
    skillTags: ["writing", "narrative", "discourse"],
  },

  // ==================== PET Listening (4 parts, Phase 2) ====================
  {
    id: "PET.L.P1",
    examType: "PET",
    paperCode: "L",
    part: 1,
    code: "L_P1_mcq_pictures",
    label: "Multiple-choice with pictures (short)",
    descriptionZh: "图片选择题（短对话）",
    skillTags: ["listening", "specific-info"],
  },
  {
    id: "PET.L.P2",
    examType: "PET",
    paperCode: "L",
    part: 2,
    code: "L_P2_mcq_medium",
    label: "Multiple-choice (medium dialogue/interview)",
    descriptionZh: "选择题（中等长度对话/访谈）",
    skillTags: ["listening", "gist", "inference"],
  },
  {
    id: "PET.L.P3",
    examType: "PET",
    paperCode: "L",
    part: 3,
    code: "L_P3_gap_fill",
    label: "Gap-fill (1-2 words/numbers/dates/times)",
    descriptionZh: "听写填空（1-2 词/数字/日期/时间）",
    skillTags: ["listening", "specific-info", "spelling"],
  },
  {
    id: "PET.L.P4",
    examType: "PET",
    paperCode: "L",
    part: 4,
    code: "L_P4_mcq_longer",
    label: "Multiple-choice (longer monologue)",
    descriptionZh: "选择题（较长独白）",
    skillTags: ["listening", "narrative", "inference"],
  },

  // ==================== PET Speaking (4 parts, Phase 3) ====================
  {
    id: "PET.S.P1",
    examType: "PET",
    paperCode: "S",
    part: 1,
    code: "S_P1_interview",
    label: "Interview with examiner",
    descriptionZh: "考官面试",
    skillTags: ["speaking", "interaction"],
  },
  {
    id: "PET.S.P2",
    examType: "PET",
    paperCode: "S",
    part: 2,
    code: "S_P2_photo",
    label: "Describe a photograph (solo)",
    descriptionZh: "描述照片（单人）",
    skillTags: ["speaking", "description", "vocabulary"],
  },
  {
    id: "PET.S.P3",
    examType: "PET",
    paperCode: "S",
    part: 3,
    code: "S_P3_collaborative",
    label: "Collaborative task with partner",
    descriptionZh: "双人协作任务",
    skillTags: ["speaking", "interaction", "negotiation"],
  },
  {
    id: "PET.S.P4",
    examType: "PET",
    paperCode: "S",
    part: 4,
    code: "S_P4_two_way",
    label: "Two-way conversation (follow-up)",
    descriptionZh: "双向对话（后续讨论）",
    skillTags: ["speaking", "opinion", "discourse"],
  },
];
